language: node_js

node_js:
 - node
 - 5
 - 4

sudo: false

before_deploy:
 - npm run typedoc
deploy:
  skip_cleanup: true
  provider: surge
  project: ./typedoc/
  domain: node-sql-template-strings.surge.sh
