language: node_js

node_js:
 - node
 - 5
 - 4

sudo: false

script:
 - npm run cover

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info'

before_deploy:
 - npm run typedoc
deploy:
  skip_cleanup: true
  provider: surge
  project: ./typedoc/
  domain: node-sql-template-strings.surge.sh
